using Microsoft.Extensions.Configuration;

namespace Platform.Shared.Jobs;

/// <summary>
/// W-42: the keys that sign and verify Hangfire job rows (<see cref="JobAuthenticity"/>). Both hosts hold them, from
/// configuration, never from the database: <c>Jobs:SigningKey</c> signs every job and verifies it, and
/// <c>Jobs:PreviousSigningKey</c>, when set, still verifies jobs signed before a key change. Each is base64 of at least
/// 32 bytes, a secret (user secrets or the secret store, N-10): SQL injected as the application role can read and write
/// Hangfire's tables but never configuration, so it cannot sign a row the worker accepts. The value is never printed,
/// logged or part of a message.
/// </summary>
public sealed class JobSigningKeys
{
    public const string SigningKeySetting = "Jobs:SigningKey";

    public const string PreviousSigningKeySetting = "Jobs:PreviousSigningKey";

    public const int MinKeyBytes = 32;

    private JobSigningKeys(byte[] current, byte[]? previous)
    {
        Current = current;
        Previous = previous;
    }

    /// <summary>The key every new job is signed with.</summary>
    internal byte[] Current { get; }

    /// <summary>A key a job may still carry a signature of, after <see cref="Current"/> replaced it; null when unset.</summary>
    internal byte[]? Previous { get; }

    /// <summary>The keys from configuration; refuses a missing or short <c>Jobs:SigningKey</c> and a malformed previous key.</summary>
    public static JobSigningKeys FromConfiguration(IConfiguration configuration)
    {
        ArgumentNullException.ThrowIfNull(configuration);
        var current = Decode(configuration[SigningKeySetting])
            ?? throw new InvalidOperationException(Problem(SigningKeySetting));
        var previousValue = configuration[PreviousSigningKeySetting];
        byte[]? previous = null;
        if (!string.IsNullOrWhiteSpace(previousValue))
        {
            previous = Decode(previousValue) ?? throw new InvalidOperationException(Problem(PreviousSigningKeySetting));
        }

        return new JobSigningKeys(current, previous);
    }

    /// <summary>Keys from raw bytes (tests); the same length rule as configuration.</summary>
    public static JobSigningKeys FromBytes(byte[] current, byte[]? previous = null)
    {
        ArgumentNullException.ThrowIfNull(current);
        if (current.Length < MinKeyBytes || previous is { Length: < MinKeyBytes })
        {
            throw new ArgumentException($"A job signing key has at least {MinKeyBytes} bytes.");
        }

        return new JobSigningKeys([.. current], previous is null ? null : [.. previous]);
    }

    /// <summary>Never the key (N-10).</summary>
    public override string ToString() => nameof(JobSigningKeys);

    private static string Problem(string setting) =>
        $"Setting '{setting}' is missing or is not a base64 key of at least {MinKeyBytes} bytes. Both Platform.Web and Platform.Worker "
        + "need the same Jobs:SigningKey to sign and verify background jobs (W-42); set it with dotnet user-secrets (docs/07 section 4). "
        + "It is never generated by the app or kept in the repository.";

    private static byte[]? Decode(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var trimmed = value.Trim();
        var buffer = new byte[((trimmed.Length * 3) / 4) + 3];
        return Convert.TryFromBase64String(trimmed, buffer, out var written) && written >= MinKeyBytes ? buffer[..written] : null;
    }
}
