"""Three fictional tenders with three offers each, and the answer key an AI review should reproduce.

Blocks: ("h", text) heading, ("p", text) paragraph, ("t", rows) table, ("br",) page break.
Every company, number, and person here is invented. Verdicts: met, partial, not_met, unclear.
"""

AR_FOOTER = "بيانات اختبارية وهمية لأغراض الاختبار فقط"
EN_FOOTER = "Fictional test data, for testing only"


def ar_docs_table(cr_expiry, vat="مرفقة", zakat="سارية حتى 2027-04-30", gosi="مرفقة", extra=None):
    rows = [["المستند", "الحالة", "تاريخ الانتهاء"],
            ["السجل التجاري", "مرفق", cr_expiry],
            ["شهادة تسجيل ضريبة القيمة المضافة", vat, "لا ينطبق"],
            ["شهادة الزكاة", zakat, ""],
            ["شهادة التأمينات الاجتماعية", gosi, "2027-01-31"]]
    return rows + (extra or [])


# ---------------------------------------------------------------- T1 network, Riyadh, Arabic
T1_RFP = [
    ("h", "كراسة الشروط والمواصفات: منافسة رقم RFP-2026-201"),
    ("p", "الجهة المالكة: شركة الواحة للتطوير العقاري، الرياض."),
    ("p", "موضوع المنافسة: توريد وتركيب وتشغيل شبكة البيانات للمقر الرئيسي المكون من ستة طوابق."),
    ("h", "1. المواعيد"),
    ("t", [["الحدث", "التاريخ"],
           ["آخر موعد لاستلام الاستفسارات", "2026-10-10"],
           ["آخر موعد لتقديم العروض", "2026-10-20 الساعة 12:00 ظهرا"],
           ["فتح المظاريف الفنية", "2026-10-21"]]),
    ("p", "يقدم العرض في مظروفين منفصلين: فني ومالي. لا يجوز ذكر أي أسعار في العرض الفني، ويستبعد العرض المخالف."),
    ("br",),
    ("h", "2. المتطلبات النظامية (إلزامية)"),
    ("t", [["الرقم", "المتطلب"],
           ["M-01", "سجل تجاري ساري المفعول حتى تاريخ تقديم العروض"],
           ["M-02", "شهادة تسجيل في ضريبة القيمة المضافة"],
           ["M-03", "شهادة الزكاة سارية"],
           ["M-04", "شهادة التأمينات الاجتماعية سارية"],
           ["M-05", "شهادة نطاقات بالنطاق الأخضر أو أعلى"],
           ["M-06", "ضمان ابتدائي بنكي بنسبة 2% من قيمة العرض ساري لمدة 90 يوما"]]),
    ("h", "3. المتطلبات الفنية"),
    ("t", [["الرقم", "المتطلب"],
           ["T-01", "توريد 24 محول شبكة بعدد 48 منفذا لكل محول مع دعم PoE+ وفق معيار IEEE 802.3at أو أعلى"],
           ["T-02", "توريد محولي قلب شبكة (عدد 2) بتكرار كامل Redundancy"],
           ["T-03", "ضمان من الشركة المصنعة لمدة خمس سنوات على جميع الأجهزة"],
           ["T-04", "دعم فني على مدار الساعة 24/7 باللغة العربية، وزمن استجابة لا يتجاوز 4 ساعات للأعطال الحرجة"],
           ["T-05", "مدة تنفيذ لا تتجاوز 90 يوما من تاريخ أمر الشراء"],
           ["T-06", "تدريب 8 موظفين من إدارة تقنية المعلومات لمدة 5 أيام"],
           ["T-07", "مهندس مشروع حاصل على شهادة CCNP أو ما يعادلها وخبرة لا تقل عن 7 سنوات"],
           ["T-08", "تسليم المخططات النهائية As-built خلال 14 يوما من الاستلام الابتدائي"]]),
    ("br",),
    ("h", "4. معايير التقييم الفني"),
    ("t", [["المعيار", "الوزن"],
           ["المطابقة الفنية", "40"],
           ["الخبرة وفريق العمل", "20"],
           ["خطة التنفيذ", "20"],
           ["الدعم الفني والضمان", "20"]]),
    ("p", "الحد الأدنى للنجاح الفني 70 درجة من 100. يفتح المظروف المالي للعروض الناجحة فنيا فقط. الترسية على أساس 60% فني و40% مالي."),
    ("h", "5. جدول الكميات (للمظروف المالي)"),
    ("t", [["البند", "الوحدة", "الكمية"],
           ["محول شبكة 48 منفذ PoE+", "وحدة", "24"],
           ["محول قلب شبكة", "وحدة", "2"],
           ["التركيب والتشغيل", "مقطوعية", "1"],
           ["التدريب", "مقطوعية", "1"],
           ["الدعم الفني لثلاث سنوات", "مقطوعية", "1"]]),
]

T1_V1_TECH = [
    ("h", "العرض الفني: شركة الأفق للحلول التقنية"),
    ("p", "إشارة إلى المنافسة رقم RFP-2026-201، نتشرف بتقديم عرضنا الفني لتوريد وتركيب شبكة البيانات. للتواصل: م. سامي العتيبي، جوال +966 55 010 0101."),
    ("h", "1. المستندات النظامية"),
    ("t", ar_docs_table("2027-05-01", extra=[["شهادة نطاقات", "النطاق البلاتيني", "2027-02-28"],
                                             ["الضمان الابتدائي", "خطاب ضمان بنكي 2% ساري 90 يوما", "2027-01-18"]])),
    ("br",),
    ("h", "2. الحل الفني"),
    ("p", "نورد 24 محولا من طراز Cisco Catalyst 9300-48P بعدد 48 منفذا لكل محول مع دعم PoE+ وفق IEEE 802.3at."),
    ("p", "نورد محولي قلب من طراز Cisco Catalyst 9500 يعملان بتقنية StackWise Virtual لتوفير تكرار كامل دون نقطة فشل واحدة."),
    ("p", "الضمان: خمس سنوات من الشركة المصنعة على جميع الأجهزة عبر عقد Cisco Smart Net Total Care."),
    ("p", "الدعم الفني: مركز دعم يعمل 24/7 باللغة العربية، وزمن الاستجابة ساعتان للأعطال الحرجة."),
    ("h", "3. خطة التنفيذ"),
    ("p", "مدة التنفيذ 75 يوما من تاريخ أمر الشراء: 20 يوما للتوريد، 40 يوما للتركيب، 15 يوما للاختبار والتسليم."),
    ("p", "التدريب: 5 أيام لعدد 8 موظفين في مقر العميل. نسلم المخططات النهائية As-built خلال 14 يوما من الاستلام الابتدائي."),
    ("h", "4. فريق العمل"),
    ("p", "مدير المشروع م. سامي العتيبي، حاصل على شهادة CCNP Enterprise وخبرة 10 سنوات في مشاريع مماثلة."),
]
T1_V1_FIN = [
    ("h", "العرض المالي: شركة الأفق للحلول التقنية"),
    ("t", [["البند", "الكمية", "سعر الوحدة", "الإجمالي"],
           ["محول شبكة 48 منفذ PoE+", "24", "21,500", "516,000"],
           ["محول قلب شبكة", "2", "95,000", "190,000"],
           ["التركيب والتشغيل", "1", "60,000", "60,000"],
           ["التدريب", "1", "15,000", "15,000"],
           ["الدعم الفني لثلاث سنوات", "1", "45,000", "45,000"],
           ["المجموع قبل الضريبة", "", "", "826,000"],
           ["ضريبة القيمة المضافة 15%", "", "", "123,900"],
           ["الإجمالي شامل الضريبة", "", "", "949,900"]]),
    ("p", "الأسعار بالريال السعودي وسارية لمدة 90 يوما."),
]

T1_SHARED_METHOD = "نعتمد منهجية تنفيذ مرحلية تبدأ بالمسح الميداني ثم التصميم التفصيلي ثم التوريد والتركيب، مع اجتماع أسبوعي مع العميل وتقرير إنجاز مكتوب في نهاية كل مرحلة."

T1_V2_TECH = [
    ("h", "العرض الفني: مؤسسة الربط المتقدم للاتصالات"),
    ("p", "بالإشارة إلى المنافسة رقم RFP-2026-201 نقدم عرضنا الفني. للتواصل: هاتف +966 11 555 0142."),
    ("h", "1. المستندات النظامية"),
    ("t", ar_docs_table("2027-08-15", zakat="قيد التجديد", extra=[["شهادة نطاقات", "النطاق الأصفر", "2026-12-31"],
                                                                ["الضمان الابتدائي", "خطاب ضمان بنكي 2%", "2027-01-20"]])),
    ("br",),
    ("h", "2. الحل الفني"),
    ("p", "نورد 24 محولا من طراز HPE Aruba CX 6200F بعدد 48 منفذا مع دعم PoE+ وفق IEEE 802.3at."),
    ("p", "نورد محول قلب واحد من طراز Aruba CX 8360 مع إمكانية إضافة محول ثان مستقبلا عند الحاجة."),
    ("p", "الضمان: ثلاث سنوات من الشركة المصنعة، وسنتان إضافيتان من المؤسسة."),
    ("p", "الدعم الفني: خلال ساعات العمل الرسمية من الأحد إلى الخميس، مع خط ساخن 24/7 باللغة الإنجليزية."),
    ("h", "3. خطة التنفيذ"),
    ("p", T1_SHARED_METHOD),
    ("p", "مدة التنفيذ 100 يوم. التدريب 3 أيام لعدد 8 موظفين. تسليم المخططات النهائية خلال 30 يوما."),
    ("h", "4. فريق العمل"),
    ("p", "مهندس المشروع حاصل على شهادة CCNA وخبرة 5 سنوات."),
]
T1_V2_FIN = [
    ("h", "العرض المالي: مؤسسة الربط المتقدم للاتصالات"),
    ("t", [["البند", "الكمية", "سعر الوحدة", "الإجمالي"],
           ["محول شبكة 48 منفذ PoE+", "24", "17,800", "427,200"],
           ["محول قلب شبكة", "1", "88,000", "88,000"],
           ["التركيب والتشغيل", "1", "55,000", "55,000"],
           ["التدريب", "1", "9,000", "9,000"],
           ["الدعم الفني لثلاث سنوات", "1", "36,000", "36,000"],
           ["المجموع قبل الضريبة", "", "", "615,200"],
           ["ضريبة القيمة المضافة 15%", "", "", "92,280"],
           ["الإجمالي شامل الضريبة", "", "", "707,480"]]),
]

T1_V3_TECH = [
    ("h", "العرض الفني: شركة النخبة للأنظمة المتكاملة"),
    ("p", "نتقدم بعرضنا للمنافسة رقم RFP-2026-201. للتواصل: هاتف +966 11 555 0142."),
    ("h", "1. المستندات النظامية"),
    ("t", ar_docs_table("2026-03-15", extra=[["شهادة نطاقات", "النطاق الأخضر", "2027-03-31"]])),
    ("br",),
    ("h", "2. الحل الفني"),
    ("p", "سيتم توريد أجهزة شبكات ذات جودة عالية من أفضل الماركات العالمية وفق أفضل الممارسات، بما يلبي احتياجات العميل."),
    ("p", "سيتم توفير محولات القلب اللازمة بما يضمن استمرارية الخدمة."),
    ("p", "الضمان حسب سياسة الشركة المصنعة. الدعم الفني متوفر عند الطلب."),
    ("h", "3. خطة التنفيذ"),
    ("p", T1_SHARED_METHOD),
    ("p", "سيتم إسناد أعمال التركيب إلى مقاول من الباطن هو مؤسسة الربط المتقدم للاتصالات. مدة التنفيذ 90 يوما."),
    ("p", "سيتم تقديم التدريب اللازم وتسليم المخططات بعد انتهاء المشروع."),
]
T1_V3_FIN = [
    ("h", "العرض المالي: شركة النخبة للأنظمة المتكاملة"),
    ("t", [["البند", "الكمية", "سعر الوحدة", "الإجمالي"],
           ["محول شبكة 48 منفذ PoE+", "24", "16,000", "348,000"],
           ["محول قلب شبكة", "2", "70,000", "140,000"],
           ["التركيب والتشغيل", "1", "مشمول", "مشمول"],
           ["الدعم الفني لثلاث سنوات", "1", "30,000", "30,000"],
           ["المجموع قبل الضريبة", "", "", "518,000"],
           ["ضريبة القيمة المضافة 15%", "", "", "77,700"],
           ["الإجمالي شامل الضريبة", "", "", "595,700"]]),
]

# ---------------------------------------------------------------- T2 cleaning, Jeddah, Arabic
T2_RFP = [
    ("h", "كراسة الشروط والمواصفات: منافسة رقم RFP-2026-305"),
    ("p", "الجهة المالكة: مجموعة البحر الأحمر للضيافة، جدة."),
    ("p", "موضوع المنافسة: خدمات النظافة الشاملة للمبنيين (أ) و(ب) لمدة 12 شهرا، بمساحة إجمالية 38,000 متر مربع."),
    ("t", [["الحدث", "التاريخ"],
           ["آخر موعد لاستلام الاستفسارات", "2026-10-15"],
           ["آخر موعد لتقديم العروض", "2026-10-29 الساعة 10:00 صباحا"],
           ["بداية العقد", "2027-01-01"]]),
    ("p", "يقدم العرض في مظروفين منفصلين: فني ومالي."),
    ("br",),
    ("h", "المتطلبات النظامية (إلزامية)"),
    ("t", [["الرقم", "المتطلب"],
           ["M-01", "سجل تجاري ساري يتضمن نشاط التنظيف"],
           ["M-02", "شهادة تسجيل في ضريبة القيمة المضافة"],
           ["M-03", "شهادة الزكاة سارية"],
           ["M-04", "شهادة التأمينات الاجتماعية سارية باسم المتقدم"],
           ["M-05", "رخصة بلدية سارية لنشاط التنظيف طوال مدة العقد"],
           ["M-06", "ضمان ابتدائي بنكي بنسبة 1% من قيمة العرض"]]),
    ("h", "المتطلبات الفنية"),
    ("t", [["الرقم", "المتطلب"],
           ["T-01", "40 عامل نظافة و4 مشرفين بدوام كامل"],
           ["T-02", "تغطية على مدار 24 ساعة طوال أيام الأسبوع للمبنيين"],
           ["T-03", "مواد تنظيف صديقة للبيئة ومسجلة لدى الجهات المختصة"],
           ["T-04", "زمن استجابة لا يتجاوز 30 دقيقة للبلاغات الطارئة"],
           ["T-05", "تدريب العمالة على السلامة المهنية قبل المباشرة"],
           ["T-06", "سكن ونقل العمالة على حساب المقاول"],
           ["T-07", "نظام إلكتروني لمتابعة البلاغات مع تقارير شهرية"],
           ["T-08", "خبرة في 3 عقود مماثلة على الأقل خلال آخر 5 سنوات"]]),
    ("br",),
    ("h", "معايير التقييم الفني"),
    ("t", [["المعيار", "الوزن"],
           ["القوى العاملة", "30"],
           ["المنهجية وخطة العمل", "25"],
           ["الخبرة السابقة", "25"],
           ["الجودة والسلامة", "20"]]),
    ("h", "جدول الكميات (للمظروف المالي)"),
    ("t", [["البند", "الوحدة", "الكمية"],
           ["العمالة والمشرفون", "شهر", "12"],
           ["مواد ومعدات التنظيف", "شهر", "12"],
           ["نظام متابعة البلاغات", "شهر", "12"]]),
]

T2_V1_TECH = [
    ("h", "العرض الفني: شركة لمعة للخدمات المتكاملة"),
    ("p", "للتواصل: أ. نورة الزهراني، جوال +966 55 020 0202."),
    ("h", "المستندات النظامية"),
    ("t", ar_docs_table("2028-02-10", extra=[["رخصة البلدية لنشاط التنظيف", "مرفقة", "2028-01-31"],
                                             ["الضمان الابتدائي", "خطاب ضمان بنكي 1%", "2027-01-27"]])),
    ("br",),
    ("h", "القوى العاملة والتغطية"),
    ("p", "نوفر 42 عامل نظافة و4 مشرفين بدوام كامل، موزعين على ثلاث نوبات لتغطية 24 ساعة طوال أيام الأسبوع في المبنيين."),
    ("p", "زمن الاستجابة للبلاغات الطارئة 20 دقيقة، مع فريق طوارئ مقيم في كل مبنى."),
    ("h", "الجودة والسلامة"),
    ("p", "نستخدم مواد تنظيف صديقة للبيئة مسجلة لدى الهيئة العامة للغذاء والدواء، ونرفق قائمة المواد وشهاداتها."),
    ("p", "يخضع كل عامل لبرنامج تدريب على السلامة المهنية مدته 3 أيام قبل المباشرة."),
    ("p", "السكن والنقل على حساب الشركة بالكامل."),
    ("p", "نظام بلاغ الإلكتروني لمتابعة البلاغات، مع تقرير أداء شهري يسلم في أول يوم عمل من كل شهر."),
    ("h", "الخبرة السابقة"),
    ("t", [["العميل", "المدة", "المساحة"],
           ["فندق الشاطئ الذهبي، جدة", "2022 إلى 2025", "25,000 م2"],
           ["أبراج المرجان المكتبية، جدة", "2023 إلى الآن", "40,000 م2"],
           ["مستشفى الرعاية الخاص، مكة", "2021 إلى 2024", "30,000 م2"],
           ["مجمع النخيل التجاري، جدة", "2024 إلى الآن", "18,000 م2"],
           ["جامعة أهلية، جدة", "2020 إلى 2023", "45,000 م2"]]),
]
T2_V1_FIN = [
    ("h", "العرض المالي: شركة لمعة للخدمات المتكاملة"),
    ("t", [["البند", "الكمية", "السعر الشهري", "الإجمالي"],
           ["العمالة والمشرفون (46 فردا)", "12", "179,400", "2,152,800"],
           ["مواد ومعدات التنظيف", "12", "18,000", "216,000"],
           ["نظام متابعة البلاغات", "12", "2,000", "24,000"],
           ["المجموع قبل الضريبة", "", "", "2,392,800"],
           ["ضريبة القيمة المضافة 15%", "", "", "358,920"],
           ["الإجمالي شامل الضريبة", "", "", "2,751,720"]]),
]

T2_V2_TECH = [
    ("h", "العرض الفني: مؤسسة الواحة البيضاء للنظافة"),
    ("p", "للتواصل: هاتف +966 12 600 0303."),
    ("h", "المستندات النظامية"),
    ("t", ar_docs_table("2027-06-30", extra=[["رخصة البلدية لنشاط التنظيف", "مرفقة", "2026-11-30"],
                                             ["الضمان الابتدائي", "خطاب ضمان بنكي 1%", "2027-01-27"]])),
    ("br",),
    ("h", "القوى العاملة"),
    ("p", "نوفر 32 عامل نظافة ومشرفين اثنين، على نوبتين من السادسة صباحا حتى منتصف الليل."),
    ("p", "زمن الاستجابة للبلاغات الطارئة 60 دقيقة."),
    ("h", "الجودة والسلامة"),
    ("p", "نستخدم مواد تنظيف صديقة للبيئة ومسجلة. يتلقى العمال تدريبا على السلامة في أسبوعهم الأول."),
    ("p", "السكن على حساب المؤسسة، أما النقل اليومي للعمالة فيتحمله العميل."),
    ("p", "نرسل تقريرا شهريا بصيغة Excel يتضمن البلاغات وأوقات إغلاقها."),
    ("h", "الخبرة السابقة"),
    ("p", "عقدان مماثلان: مجمع الروضة السكني (2023 إلى الآن) ومبنى إداري في حي الحمراء (2024 إلى الآن)."),
]
T2_V2_FIN = [
    ("h", "العرض المالي: مؤسسة الواحة البيضاء للنظافة"),
    ("t", [["البند", "الكمية", "السعر الشهري", "الإجمالي"],
           ["العمالة والمشرفون (34 فردا)", "12", "108,800", "1,305,600"],
           ["مواد ومعدات التنظيف", "12", "12,000", "144,000"],
           ["المجموع قبل الضريبة", "", "", "1,449,600"],
           ["ضريبة القيمة المضافة 15%", "", "", "217,440"],
           ["الإجمالي شامل الضريبة", "", "", "1,667,040"]]),
]

T2_V3_TECH = [
    ("h", "العرض الفني: شركة الأمانة للتشغيل والصيانة"),
    ("p", "للتواصل: هاتف +966 12 600 0404."),
    ("h", "المستندات النظامية"),
    ("t", ar_docs_table("2027-09-01", gosi="مرفقة باسم شركة الأمانة لتوريد العمالة",
                        extra=[["رخصة البلدية لنشاط التنظيف", "مرفقة", "2027-12-31"],
                               ["الضمان الابتدائي", "خطاب ضمان بنكي 1%", "2027-01-27"]])),
    ("br",),
    ("h", "المنهجية"),
    ("p", "سيتم توفير العدد الكافي من العمالة والمشرفين حسب حاجة العمل وبما يحقق رضا العميل."),
    ("p", "سيتم توريد العمالة عن طريق شركة شقيقة متخصصة في توريد العمالة بموجب عقد من الباطن."),
    ("p", "التغطية حسب ساعات العمل المتفق عليها مع العميل. الاستجابة للبلاغات فورية."),
    ("p", "نستخدم أفضل مواد التنظيف المتوفرة في السوق."),
    ("h", "الخبرة السابقة"),
    ("p", "لدينا خبرة واسعة في مجال التشغيل والصيانة لدى عدد كبير من الجهات الحكومية والخاصة."),
]
T2_V3_FIN = [
    ("h", "العرض المالي: شركة الأمانة للتشغيل والصيانة"),
    ("t", [["البند", "الكمية", "السعر الشهري", "الإجمالي"],
           ["الخدمة الشاملة (عمالة ومواد ونظام)", "12", "150,000", "1,650,000"],
           ["المجموع قبل الضريبة", "", "", "1,650,000"],
           ["ضريبة القيمة المضافة 15%", "", "", "247,500"],
           ["الإجمالي شامل الضريبة", "", "", "1,897,500"]]),
]

# ---------------------------------------------------------------- T3 HR and payroll SaaS, English
T3_RFP = [
    ("h", "Request for Proposal RFP-2026-412: HR and Payroll Software"),
    ("p", "Issuer: Najd Logistics Company, Riyadh. 600 employees across 4 branches."),
    ("p", "Scope: a cloud HR and payroll system covering employee records, payroll, leave, self-service, and government integrations, with implementation and data migration from Excel."),
    ("t", [["Event", "Date"],
           ["Questions deadline", "2026-10-12"],
           ["Proposal deadline", "2026-10-26 14:00"],
           ["Go-live target", "2027-03-01"]]),
    ("p", "Submit technical and financial proposals as separate files. Any price in the technical proposal disqualifies it."),
    ("br",),
    ("h", "Mandatory requirements"),
    ("t", [["ID", "Requirement"],
           ["M-01", "Valid commercial registration"],
           ["M-02", "VAT registration certificate"],
           ["M-03", "Valid Zakat certificate"],
           ["M-04", "Valid GOSI certificate"],
           ["M-05", "Signed non-disclosure agreement (template attached)"]]),
    ("h", "Technical requirements"),
    ("t", [["ID", "Requirement"],
           ["T-01", "Payroll compliant with GOSI and generating WPS files through Mudad"],
           ["T-02", "Full Arabic and English user interface with right-to-left support on web and mobile"],
           ["T-03", "Customer data hosted in a data centre inside Saudi Arabia, compliant with PDPL and NCA ECC"],
           ["T-04", "Single sign-on with Microsoft Entra ID"],
           ["T-05", "Employee self-service mobile app for iOS and Android"],
           ["T-06", "Implementation including data migration within 120 days"],
           ["T-07", "Availability SLA of at least 99.9 percent with service credits"],
           ["T-08", "Three reference customers in Saudi Arabia with 500 or more employees"]]),
    ("br",),
    ("h", "Evaluation criteria"),
    ("t", [["Criterion", "Weight"],
           ["Functional fit", "40"],
           ["Compliance and hosting", "20"],
           ["Implementation plan", "20"],
           ["References", "20"]]),
    ("p", "Technical pass mark 70 out of 100. Award on 70 percent technical and 30 percent financial."),
    ("h", "Price schedule (financial proposal)"),
    ("t", [["Item", "Unit", "Quantity"],
           ["Subscription", "user per month", "600 users x 12 months"],
           ["Implementation", "lump sum", "1"],
           ["Data migration", "lump sum", "1"],
           ["Training", "lump sum", "1"]]),
]

T3_SHARED_TEXT = ("Our platform is built for Saudi employers: every payroll run is validated against the latest GOSI rules, "
                  "and WPS files are generated and submitted through Mudad without manual steps.")

T3_V1_TECH = [
    ("h", "Technical Proposal: Cedar HR Cloud"),
    ("p", "Contact: Faisal Al-Harbi, +966 55 030 0505."),
    ("h", "1. Company documents"),
    ("t", [["Document", "Status", "Expiry"],
           ["Commercial registration", "Attached", "2027-11-30"],
           ["VAT certificate", "Attached", "n/a"],
           ["Zakat certificate", "Attached", "2027-04-30"],
           ["GOSI certificate", "Attached", "2027-01-31"],
           ["Signed NDA", "Attached", "n/a"]]),
    ("br",),
    ("h", "2. Functional fit"),
    ("p", T3_SHARED_TEXT),
    ("p", "The interface is fully bilingual, Arabic and English, with right-to-left layouts on web, iOS, and Android."),
    ("p", "Single sign-on with Microsoft Entra ID through OpenID Connect, live at 14 customers."),
    ("p", "The self-service app is published on the App Store and Google Play."),
    ("h", "3. Hosting and compliance"),
    ("p", "All customer data is hosted in our Riyadh data centre. We hold the NCA ECC compliance report and a PDPL data processing agreement is attached."),
    ("p", "SLA: 99.95 percent monthly availability, with a 10 percent service credit for each 0.1 percent below target."),
    ("h", "4. Implementation"),
    ("p", "Go-live in 105 days, including migration of employee and payroll history from Excel, in four phases."),
    ("h", "5. References"),
    ("t", [["Customer", "Employees", "Since"],
           ["Retail group, Riyadh", "2,400", "2023"],
           ["Private hospital, Dammam", "900", "2024"],
           ["Contracting company, Jeddah", "650", "2022"]]),
]
T3_V1_FIN = [
    ("h", "Financial Proposal: Cedar HR Cloud"),
    ("t", [["Item", "Quantity", "Unit price (SAR)", "Total (SAR)"],
           ["Subscription, per user per month", "7,200", "18", "129,600"],
           ["Implementation", "1", "85,000", "85,000"],
           ["Data migration", "1", "20,000", "20,000"],
           ["Training", "1", "15,000", "15,000"],
           ["Subtotal", "", "", "249,600"],
           ["VAT 15%", "", "", "37,440"],
           ["Total", "", "", "287,040"]]),
]

T3_V2_TECH = [
    ("h", "Technical Proposal: PeoplePulse Systems"),
    ("p", "Contact: sales team, +966 11 700 0606."),
    ("h", "1. Company documents"),
    ("t", [["Document", "Status", "Expiry"],
           ["Commercial registration", "Attached", "2028-01-15"],
           ["VAT certificate", "Attached", "n/a"],
           ["Zakat certificate", "Attached", "2027-04-30"],
           ["GOSI certificate", "Attached", "2027-02-28"],
           ["Signed NDA", "Attached", "n/a"]]),
    ("br",),
    ("h", "2. Functional fit"),
    ("p", "Payroll supports GOSI calculations. WPS files are produced by our partner integration and uploaded to Mudad by the customer."),
    ("p", "Arabic is available on the web application with right-to-left layout. The mobile app is English only in the current release."),
    ("p", "Single sign-on with Microsoft Entra ID through SAML 2.0. Mobile apps for iOS and Android."),
    ("h", "3. Hosting and compliance"),
    ("p", "Hosted in our Frankfurt region. A Saudi region is planned for the second quarter of 2027."),
    ("p", "SLA: 99.5 percent monthly availability."),
    ("h", "4. Implementation and references"),
    ("p", "Implementation in 150 days. References: two Saudi customers with 520 and 800 employees."),
]
T3_V2_FIN = [
    ("h", "Financial Proposal: PeoplePulse Systems"),
    ("t", [["Item", "Quantity", "Unit price (SAR)", "Total (SAR)"],
           ["Subscription, per user per year", "600", "168", "100,800"],
           ["Implementation", "1", "60,000", "60,000"],
           ["Subtotal", "", "", "160,800"],
           ["VAT 15%", "", "", "24,120"],
           ["Total", "", "", "184,920"]]),
    ("p", "Data migration and training are optional and quoted separately on request."),
]

T3_V3_TECH = [
    ("h", "Technical Proposal: Qimma Business Solutions"),
    ("p", "Contact: +966 11 700 0707."),
    ("h", "1. Company documents"),
    ("t", [["Document", "Status", "Expiry"],
           ["Commercial registration", "Attached", "2027-06-30"],
           ["Zakat certificate", "Attached", "2027-04-30"],
           ["GOSI certificate", "Attached", "2027-01-31"],
           ["Signed NDA", "Attached", "n/a"]]),
    ("br",),
    ("h", "2. Compliance statement"),
    ("p", T3_SHARED_TEXT),
    ("t", [["Requirement", "Response"],
           ["T-01", "Complies"], ["T-02", "Complies"], ["T-03", "Complies"], ["T-04", "Complies"],
           ["T-05", "Complies"], ["T-06", "Complies"], ["T-07", "Complies"], ["T-08", "Complies"]]),
    ("p", "Our solution is trusted by leading organisations across the Kingdom, including a major retailer and a large government entity."),
]
T3_V3_FIN = [
    ("h", "Financial Proposal: Qimma Business Solutions"),
    ("t", [["Item", "Quantity", "Unit price (SAR)", "Total (SAR)"],
           ["Subscription, per user per month", "7,200", "10", "72,000"],
           ["Implementation", "1", "30,000", "30,000"],
           ["Data migration", "1", "10,000", "10,000"],
           ["Training", "1", "5,000", "5,000"],
           ["Subtotal", "", "", "127,000"],
           ["VAT 15%", "", "", "19,050"],
           ["Total", "", "", "146,050"]]),
]

# ---------------------------------------------------------------- tenders, formats, answer keys
# format: docx (as submitted), pdf (Word export), scanned (image-only PDF)
M6 = ["M-01", "M-02", "M-03", "M-04", "M-05", "M-06"]
M5 = ["M-01", "M-02", "M-03", "M-04", "M-05"]
T8 = ["T-01", "T-02", "T-03", "T-04", "T-05", "T-06", "T-07", "T-08"]


def key(verdicts, ids):
    return {i: v for i, v in zip(ids, verdicts)}


TENDERS = [
    {
        "id": "T1-network-riyadh", "rtl": True, "rfp": T1_RFP, "rfp_formats": ["docx", "pdf"],
        "offers": [
            {"id": "V1-alufuq", "name": "شركة الأفق للحلول التقنية", "format": "docx", "tech": T1_V1_TECH, "fin": T1_V1_FIN,
             "expected": key(["met"] * 6 + ["met"] * 8, M6 + T8), "flags": []},
            {"id": "V2-alrabt", "name": "مؤسسة الربط المتقدم للاتصالات", "format": "pdf", "tech": T1_V2_TECH, "fin": T1_V2_FIN,
             "expected": key(["met", "met", "unclear", "met", "not_met", "met",
                              "met", "not_met", "partial", "partial", "not_met", "partial", "not_met", "not_met"], M6 + T8),
             "flags": ["financial: core switch quantity 1, BoQ asks for 2",
                       "integrity: same phone +966 11 555 0142 as V3",
                       "integrity: implementation methodology paragraph identical to V3"]},
            {"id": "V3-alnukhba", "name": "شركة النخبة للأنظمة المتكاملة", "format": "scanned", "tech": T1_V3_TECH, "fin": T1_V3_FIN,
             "expected": key(["not_met", "met", "met", "met", "met", "not_met",
                              "unclear", "unclear", "unclear", "unclear", "met", "unclear", "not_met", "unclear"], M6 + T8),
             "flags": ["compliance: commercial registration expired 2026-03-15, before the deadline",
                       "risk: vague commitments, no product models, warranty or response times",
                       "risk: installation subcontracted to another bidder in the same tender (V2)",
                       "integrity: same phone +966 11 555 0142 as V2",
                       "financial: 24 x 16,000 written as 348,000, correct is 384,000",
                       "financial: training line missing; installation priced as included"]},
        ],
    },
    {
        "id": "T2-cleaning-jeddah", "rtl": True, "rfp": T2_RFP, "rfp_formats": ["pdf"],
        "offers": [
            {"id": "V1-lamaa", "name": "شركة لمعة للخدمات المتكاملة", "format": "pdf", "tech": T2_V1_TECH, "fin": T2_V1_FIN,
             "expected": key(["met"] * 6 + ["met"] * 8, M6 + T8), "flags": []},
            {"id": "V2-alwaha", "name": "مؤسسة الواحة البيضاء للنظافة", "format": "docx", "tech": T2_V2_TECH, "fin": T2_V2_FIN,
             "expected": key(["met", "met", "met", "met", "not_met", "met",
                              "not_met", "partial", "met", "not_met", "partial", "partial", "partial", "partial"], M6 + T8),
             "flags": ["compliance: municipal licence expires 2026-11-30, before the contract starts on 2027-01-01",
                       "financial: reporting system line missing from the price schedule",
                       "financial: price about 40 percent below V1 with fewer staff than required"]},
            {"id": "V3-alamana", "name": "شركة الأمانة للتشغيل والصيانة", "format": "scanned", "tech": T2_V3_TECH, "fin": T2_V3_FIN,
             "expected": key(["met", "met", "met", "not_met", "met", "met",
                              "unclear", "unclear", "unclear", "unclear", "not_met", "not_met", "not_met", "unclear"], M6 + T8),
             "flags": ["compliance: GOSI certificate is in the name of a different company",
                       "risk: labour supplied through a sister company as subcontractor",
                       "risk: vague commitments on headcount, response time, and experience",
                       "financial: 12 x 150,000 written as 1,650,000, correct is 1,800,000",
                       "financial: single lump-sum line instead of the three BoQ lines"]},
        ],
    },
    {
        "id": "T3-hr-software", "rtl": False, "rfp": T3_RFP, "rfp_formats": ["docx"],
        "offers": [
            {"id": "V1-cedar", "name": "Cedar HR Cloud", "format": "docx", "tech": T3_V1_TECH, "fin": T3_V1_FIN,
             "expected": key(["met"] * 5 + ["met"] * 8, M5 + T8), "flags": []},
            {"id": "V2-peoplepulse", "name": "PeoplePulse Systems", "format": "pdf", "tech": T3_V2_TECH, "fin": T3_V2_FIN,
             "expected": key(["met"] * 5 + ["partial", "partial", "not_met", "met", "met", "not_met", "not_met", "partial"], M5 + T8),
             "flags": ["financial: subscription priced per user per year, schedule asks per user per month",
                       "financial: data migration and training lines missing"]},
            {"id": "V3-qimma", "name": "Qimma Business Solutions", "format": "scanned", "tech": T3_V3_TECH, "fin": T3_V3_FIN,
             "expected": key(["met", "not_met", "met", "met", "met"] + ["met"] + ["unclear"] * 6 + ["not_met"], M5 + T8),
             "flags": ["compliance: VAT certificate missing",
                       "risk: every requirement answered 'Complies' with no evidence",
                       "risk: references are unnamed",
                       "integrity: payroll paragraph identical to V1's proposal",
                       "financial: subtotal written as 127,000, correct is 117,000",
                       "financial: price less than half of V1"]},
        ],
    },
]
