namespace Platform.Modules.Vendors;

/// <summary>
/// Settings of the vendor pages (section <c>Vendors</c>), validated when the web host starts
/// (<see cref="VendorsModule.AddVendorPortal"/>):
/// <list type="bullet">
/// <item><c>Vendors:CrAuditKey</c>: the key of the duplicate-CR audit (V-6), base64, at least 32 bytes. A secret: user
/// secrets locally, the cloud KMS in production, never the repository, never logged (N-10). Changing it makes earlier
/// audit entries unmatchable with later ones.</item>
/// <item><c>Vendors:UploadRequestsPerMinute</c>: upload API requests per vendor company per minute (V-9), 120 by default.</item>
/// <item><c>Vendors:MaxUploadsPerDay</c>: uploads a vendor company may start in any 24 hours, whatever became of them
/// (V-9), 30 by default.</item>
/// <item><c>Vendors:DuplicateCrPerAddress</c>: "already registered" answers per source address in the window, whatever the
/// account (W-34), 20 by default; each account has its own limit of five as well (V-6).</item>
/// <item><c>Vendors:DuplicateCrWindow</c>: the window of both duplicate-CR limits, from the first answer, one hour by
/// default (<c>01:00:00</c>); at least one second.</item>
/// <item><c>Vendors:JoinsPerUserPerMinute</c>: joins of a tenant (<c>/vendor/join</c>) one user may make in any minute,
/// whatever the tenant (W-37), 5 by default.</item>
/// <item><c>Vendors:JoinsPerTenantPerMinute</c>: first-time joins of one tenant by all new vendors in any minute (W-37),
/// 20 by default.</item>
/// <item><c>Vendors:MaxConcurrentJoins</c>: first-time joins in flight at once in one web instance, across tenants, each
/// holding up to two pooled connections while it waits on Keycloak (W-37), 10 by default.</item>
/// <item><c>Vendors:ConsentGrantsPerCompanyPerHour</c>: consent grants one vendor company may make in any hour (W-35,
/// F-64), 30 by default; revocations are never limited (PDPL).</item>
/// </list>
/// The join and consent limits and the join cap are counted per web instance (<see cref="RateLimiting.VendorRateLimits"/>,
/// <see cref="RateLimiting.ConcurrentJoinGate"/>).
/// </summary>
internal sealed class VendorsOptions
{
    public const string Section = "Vendors";

    /// <summary>The full name of the key setting, for messages; never its value.</summary>
    public const string CrAuditKeySetting = "Vendors:CrAuditKey";

    public const int MinCrAuditKeyBytes = 32;

    public string? CrAuditKey { get; set; }

    public int UploadRequestsPerMinute { get; set; } = 120;

    public int MaxUploadsPerDay { get; set; } = 30;

    public int DuplicateCrPerAddress { get; set; } = 20;

    public TimeSpan DuplicateCrWindow { get; set; } = TimeSpan.FromHours(1);

    public int JoinsPerUserPerMinute { get; set; } = 5;

    public int JoinsPerTenantPerMinute { get; set; } = 20;

    public int MaxConcurrentJoins { get; set; } = 10;

    public int ConsentGrantsPerCompanyPerHour { get; set; } = 30;

    internal static string CrAuditKeyProblem =>
        $"Setting '{CrAuditKeySetting}' is missing or is not a base64 key of at least {MinCrAuditKeyBytes} bytes. " +
        "Set it with dotnet user-secrets on the web host (docs/07 section 4); it is never generated by the app or kept in the repository.";

    /// <summary>The key's bytes, or null when the setting is missing, not base64, or shorter than 32 bytes.</summary>
    internal static byte[]? DecodeCrAuditKey(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var buffer = new byte[((value.Length * 3) / 4) + 3];
        return Convert.TryFromBase64String(value.Trim(), buffer, out var written) && written >= MinCrAuditKeyBytes
            ? buffer[..written]
            : null;
    }
}
