<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\Migrations\*.sql" LogicalName="Migrations.%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Platform.UnitTests" />
    <InternalsVisibleTo Include="Platform.IntegrationTests" />
  </ItemGroup>
</Project>
